### ISSUE TITLE
project setup

### ISSUE THREAD

**Issue by naremanhilles** [FACG6/zajel#31]
- [ ] Setup the react server.
- [ ] connect with travis to keep our code safe and clean 
from conflict and confusing.
- [ ] Setup the express server.
- [ ] connect project to heroku link
- [ ] import the eslint and make the setup and settings for it
to make sure that the syntax is correct.
- [ ] setup database.
