### ISSUE TITLE
Add Order Component Back End 

### ISSUE THREAD

**Issue by Jamalat-shamallakh** [FACG6/zajel#45]
back end side :  
- [ ] use /addOrder as a route to : 
   - [ ] get palces as a query of a database #84
   - [ ] get customer name as a query of a databasee #85
   - [ ] get captain name as a query of a database #86

- [ ] use   /addOrder to post object which comes from the front end to the database in the order table.
- [ ] use postOrder as a query of a database #45
- [ ] send the new order as a response of the post method.
